name: Python Application

on:
  # Trigger on code push to any branch
  push:
    branches:
      - '*'  # This will trigger on push to any branch

  # Trigger on pull request creation or updates against 'master'
  pull_request:
    branches:
      - master

  # Trigger when a pull request targeting 'master' is approved
  pull_request_review:
    types:
      - approved
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest
